#spring:
#  datasource:
#    url: jdbc://postgresql://localhost:5432/walmartdb
#    username: walmart
#    password: walmart@123

app:
  postgresource:
    jdbcUrl: jdbc:postgresql://localhost:5432/walmartdb
    username: walmart
    password: walmart@123
    maxPoolSize: 15

server:
  port: 8085
  error:
    include-stacktrace: never

